require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - config.ru
    - bin/**
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Metrics:
  Exclude:
    - db/**/*

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - config.rb
    - spec/**/*

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Naming/VariableNumber:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'
    - 'spec/system/**/*_spec.rb'

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: percent
